# Generated by Django 5.1.1 on 2024-10-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_remove_education_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('detail_link', models.URLField(blank=True, null=True)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='portfolio_gallery/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='Portfolio.about')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Portfolio.portfoliocategory')),
            ],
        ),
    ]
